version: '3.8'

services:
  mysql-db:
    image: mysql:8
    container_name: mysql-container
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mypropertyfact
      MYSQL_USER: demouser
      MYSQL_PASSWORD: mysql
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-app:
    build: .
    container_name: spring-boot-app
    restart: always
    depends_on:
      - mysql-db
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/mypropertyfact
      SPRING_DATASOURCE_USERNAME: demouser
      SPRING_DATASOURCE_PASSWORD: mysql

volumes:
  mysql_data:
